version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: db
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: hiworld
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - 3306:3306

  tomcat:
    depends_on:
      - db
    build:
      context: ../lib/
      dockerfile: ../docker/webapp.dockerfile
    image: webapp
    container_name: webapp
    restart: always
    ports:
      - 8081:8080